name: 'Perform rust commands'
description: 'Performs the commands and checks the output'
inputs:
  toolchain:
    description: 'Toolchain to run'
    required: false
    default: ''
  command:
    description: 'Cargo command to trigger'
    required: true
  args:
    description: 'Arguments for cargo cmd'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.toolchain }}
    - ${{ inputs.command }}
    - ${{ inputs.args }}
