on: [pull_request]  # more suitable for private repos
#on: [push]  # push is fine for the public repos

name: Rust workflow for Example

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

# dummy action which will show the version -> remove it on production
    - name: Version
      id: version
      uses: angelcam/actions-rust@master
      with:
        command: -V
        ssh_key: ${{ secrets.ssh_key }}  # private repo access (you need to add the `ssh_key` into github)

# uncomment below

#    - name: Fmt
#      id: fmt
#      uses: angelcam/actions-rust@master
#      with:
#        command: fmt
#        args: --all -- --check
#        ssh_key: ${{ secrets.ssh_key }}
#
#    - name: Build
#      id: build
#      uses: angelcam/actions-rust@master
#      with:
#        command: build
#        args: --all-features --release
#        ssh_key: ${{ secrets.ssh_key }}
#
#    - name: Test
#      id: test
#      uses: angelcam/actions-rust@master
#      with:
#        command: test
#        args: --all-features
#        ssh_key: ${{ secrets.ssh_key }}
#
#    - name: Clippy
#      id: clippy
#      uses: angelcam/actions-rust@master
#      with:
#        command: clippy
#        args: -- -D warnings
#        ssh_key: ${{ secrets.ssh_key }}
#
#    - name: Audit
#      id: audit
#      uses: angelcam/actions-rust@master
#      with:
#        command: audit
#        ssh_key: ${{ secrets.ssh_key }}
#
#    - name: Udeps
#      id: udeps
#      uses: angelcam/actions-rust@master
#      with:
#        command: udeps
#        toolchain: +nightly
#        ssh_key: ${{ secrets.ssh_key }}
